#debug: true
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://192.168.11.104:3306/hmily_fx2?serverTimezone=Asia/Shanghai
    username: root
    password: deepwise
mybatis:
  type-aliases-package: com.marcus.dubbo.boot.userVip.entity
dubbo:
  application:
    id: provider
    name: provider
  registry:
    address: zookeeper://192.168.11.104:2181
  metadata-report:
    address: zookeeper://192.168.11.104:2181
  protocol:
    port: 20000
    name: dubbo
  monitor:
    protocol: registry
  config-center:
    timeout: 10000
logging:
  level:
    com:
      marcus:
        dubbo: info