spring:
  # 相关的配置
  shardingsphere:
    props:
      sql-show: true
    datasource:
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      # 配置数据源的名称
      names: ds1,ds2,ds3
      # 第一个数据源
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/test_db1?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: deepwise
      # 第二个数据源
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/test_db2?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: deepwise
      ds3:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/test_db3?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: deepwise
    rules:
      replica-query:
        data-sources:
          ds:
            primary-data-source-name: ds1
            replica-data-source-names: ds2,ds3
            load-balancer-name: round-robin
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              defaule: 0