#debug: true
server:
  port: 9000
dubbo:
  application:
    id: consumer
    name: consumer
  registry:
    address: zookeeper://192.168.11.104:2181
  monitor:
    protocol: registry
  metadata-report:
    address: zookeeper://192.168.11.104:2181
  config-center:
    timeout: 10000

spring:
  datasource:
    url: jdbc:mysql://192.168.11.104:3306/hmily_fx1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: deepwise